services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: erp-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: erp_auth
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - erp-network

  # Auth Service
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: erp-auth-service
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      ENVIRONMENT: development
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/erp_auth?authSource=admin
      DATABASE_NAME: erp_auth
      SECRET_KEY: ${JWT_SECRET_KEY:-your-super-secret-key-change-this-in-production}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      SERVICE_NAME: auth-service
      SERVICE_PORT: 8001
      SERVICE_HOST: 0.0.0.0
      LOG_LEVEL: INFO
    depends_on:
      - mongodb
    volumes:
      - ./auth-service:/app
    networks:
      - erp-network

  # Inventory Service
  inventory-service:
    build: 
      context: ./inventory-service
      dockerfile: Dockerfile.dev
    container_name: erp-inventory-service
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      NODE_ENV: development
      PORT: 8002
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/erp_inventory?authSource=admin
      AUTH_SERVICE_URL: http://auth-service:8001
      JWT_SECRET: ${JWT_SECRET_KEY:-your-super-secret-key-change-this-in-production}
    depends_on:
      - mongodb
      - auth-service
    volumes:
      - ./inventory-service/src:/app/src
      - ./inventory-service/package.json:/app/package.json
      - ./inventory-service/package-lock.json:/app/package-lock.json
      - ./inventory-service/tsconfig.json:/app/tsconfig.json
      - ./inventory-service/tsconfig.build.json:/app/tsconfig.build.json
      - ./inventory-service/nest-cli.json:/app/nest-cli.json
      - inventory_uploads:/app/uploads
    networks:
      - erp-network

  # Sales Service
  sales-service:
    build: 
      context: ./sales-service
      dockerfile: Dockerfile
    container_name: erp-sales-service
    restart: unless-stopped
    ports:
      - "8003:8003"
    environment:
      ENVIRONMENT: development
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/erp_sales?authSource=admin
      DATABASE_NAME: erp_sales
      AUTH_SERVICE_URL: http://auth-service:8001
      INVENTORY_SERVICE_URL: http://inventory-service:8002
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-super-secret-key-change-this-in-production}
      SERVICE_NAME: Sales Service
      SERVICE_VERSION: 1.0.0
      SERVICE_PORT: 8003
      SERVICE_HOST: 0.0.0.0
      LOG_LEVEL: INFO
      DEBUG: "true"
      DEFAULT_TAX_RATE: 0.08
      DEFAULT_CURRENCY: USD
      REDIS_URL: redis://redis:6379
      # Stripe Payment Gateway
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY:-}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
      STRIPE_API_VERSION: "2023-10-16"
      STRIPE_CURRENCY: usd
    depends_on:
      - mongodb
      - auth-service
      - inventory-service
    volumes:
      - ./sales-service:/app
    networks:
      - erp-network

  # Redis for caching and background tasks
  redis:
    image: redis:7.2-alpine
    container_name: erp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - erp-network

  # MongoDB Express (Development only)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: erp-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - erp-network
    profiles:
      - development

  # Frontend React Application (Production)
  frontend:
    build:
      context: ./erp-frontend
      dockerfile: Dockerfile
      args:
        - VITE_AUTH_SERVICE_URL=http://localhost:8001
        - VITE_INVENTORY_SERVICE_URL=http://localhost:8002
        - VITE_SALES_SERVICE_URL=http://localhost:8003
        - VITE_STRIPE_PUBLIC_KEY=${STRIPE_PUBLISHABLE_KEY:-}
    container_name: erp-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - inventory-service
      - sales-service
    networks:
      - erp-network
      
  # Frontend React Application (Development with hot-reload)
  frontend-dev:
    build:
      context: ./erp-frontend
      dockerfile: Dockerfile.dev
    container_name: erp-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_AUTH_SERVICE_URL: http://localhost:8001
      VITE_INVENTORY_SERVICE_URL: http://localhost:8002
      VITE_SALES_SERVICE_URL: http://localhost:8003
      VITE_STRIPE_PUBLIC_KEY: ${STRIPE_PUBLISHABLE_KEY:-}
    volumes:
      - ./erp-frontend/src:/app/src
      - ./erp-frontend/public:/app/public
      - ./erp-frontend/index.html:/app/index.html
      - ./erp-frontend/vite.config.ts:/app/vite.config.ts
      - ./erp-frontend/tailwind.config.js:/app/tailwind.config.js
      - ./erp-frontend/postcss.config.js:/app/postcss.config.js
      - ./erp-frontend/tsconfig.json:/app/tsconfig.json
      - ./erp-frontend/tsconfig.node.json:/app/tsconfig.node.json
    depends_on:
      - auth-service
      - inventory-service
      - sales-service
    networks:
      - erp-network
    profiles:
      - development

volumes:
  mongodb_data:
  redis_data:
  inventory_uploads:

networks:
  erp-network:
    driver: bridge
