services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: erp-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - erp-network

  # Redis
  redis:
    image: redis:7.2-alpine
    container_name: erp-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - erp-network

  # Auth Service
  auth-service:
    image: ghcr.io/mahmudul-islam32/erp-auth-service:latest
    container_name: erp-auth-service
    restart: always
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - mongodb
    networks:
      - erp-network

  # Inventory Service  
  inventory-service:
    image: ghcr.io/mahmudul-islam32/erp-inventory-service:latest
    container_name: erp-inventory-service
    restart: always
    ports:
      - "8002:8002"
    env_file: .env
    environment:
      AUTH_SERVICE_URL: http://auth-service:8001
    depends_on:
      - mongodb
      - auth-service
    volumes:
      - inventory_uploads:/app/uploads
    networks:
      - erp-network

  # Sales Service
  sales-service:
    image: ghcr.io/mahmudul-islam32/erp-sales-service:latest
    container_name: erp-sales-service
    restart: always
    ports:
      - "8003:8003"
    env_file: .env
    environment:
      AUTH_SERVICE_URL: http://auth-service:8001
      INVENTORY_SERVICE_URL: http://inventory-service:8002
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongodb
      - redis
      - auth-service
      - inventory-service
    networks:
      - erp-network

  # Frontend
  frontend:
    image: ghcr.io/mahmudul-islam32/erp-frontend:latest
    container_name: erp-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - auth-service
      - inventory-service
      - sales-service
    networks:
      - erp-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  inventory_uploads:
    driver: local

networks:
  erp-network:
    driver: bridge

